sqldriver:
    driver: com.mysql.cj.jdbc.Driver
    path: jdbc:mysql://localhost:3306/devshub
    userName: root
    passWord: "#Lekoso00"

#articlesdb:
#    driver: com.mysql.cj.jdbc.Driver
#    path: jdbc:mysql://localhost:3306/articles
#    userName: root
#    passWord: "#Lekoso00"